server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    #http://localhost:8080/h2-console
    console.enabled: true

movies:
  apiKey: "a7c0b9a6"
  maxToLoad: 10
  gzipMoviesFile: "title.ratings.tsv.gz"